Feature: Add Remote Modal Widget
CottaCush/yii2-widgets pull request #12
Opened 2017-09-20 14:23 UTC by yemexx1

2017-09-20 14:35 UTC, netwox approved these changes

2017-09-21 16:06 UTC, olajideoye requested changes
There're a few things to clean up

2017-09-21 16:06 UTC, olajideoye commented on src/Assets/AppAsset.php
> +<?php
@yemexx1  I don't think this asset is needed here. In reality, the app asset definition could vary according to the project.

2017-09-21 16:06 UTC, olajideoye commented on src/Assets/AppModuleAsset.php
> +        'CottaCush\Yii2\Assets\AppAsset'
@yemexx1 The dependency here should be the `yii\web\JqueryAsset`

2017-09-21 16:06 UTC, olajideoye commented on src/Assets/AppModuleAsset.php
> + * @author Olajide Oye <jide@cottacush.com>
@yemexx1 Please add yourself as the author :)

2017-09-21 16:06 UTC, olajideoye commented on src/Widgets/BaseIcon.php
> +<?php
@yemexx1 The use for this widget has been replaced with a static function in the `CottaCush\Yii2\Helpers\Html` class.

2017-09-21 16:06 UTC, olajideoye commented on src/Widgets/BaseRemoteModalWidget.php
> +use yii\bootstrap\Html;
@yemexx1 Could we use the `CottaCush\Yii2\Helpers\Html` class instead?

2017-09-21 16:06 UTC, olajideoye commented on src/Widgets/FontAwesomeIcon.php
> +<?php
@yemexx1 The use of this widget has been replaced with a static function on the `CottaCush\Yii2\Helpers\Html` class

2017-09-21 16:06 UTC, olajideoye commented on src/Widgets/RemoteModalFormWidget.php
> +use yii\helpers\Html;
Please replace this class with the `CottaCush\Yii2\Helpers\Html` class

2017-09-21 16:06 UTC, olajideoye commented on src/Widgets/RemoteModalPlaceholderWidget.php
> +use yii\helpers\Html;
Please use the `CottaCush\Yii2\Helpers\Html` class

2017-09-21 16:06 UTC, olajideoye commented on src/Widgets/RemoteModalWidget.php
> +use yii\helpers\Html;
@yemexx1 Please use the `CottaCush\Yii2\Helpers\Html` class

2017-10-09 12:37 UTC, goke-epapa approved these changes

2017-10-09 12:59 UTC, olajideoye approved these changes
Looks good to merge!

2017-10-09 13:00 UTC, merged